name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '2'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install modules
        run: pnpm install
      - name: Check changed files
        uses: actions/github-script@v6
        with:
          script: |
            const { execSync } = require('child_process')
            const { commits } = context.payload.pull_request
            console.log(commits)
            const rawFiles = execSync(`git diff-tree --no-commit-id --name-only -r HEAD`).toString()
            const files = rawFiles.split('\n').filter(Boolean)
            
            console.log(files)
