name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install modules
        run: pnpm install
      - name: Check for automated commit
        run: echo $(git diff-tree --no-commit-id --name-only -r HEAD)
      - name: Check changed files
        uses: actions/github-script@v6
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
        with:
          script: |
            const script = require('.github/scripts/main.js')
            script({github, context})
            
